### PR TITLE
Instruction details fix

### LINKED ISSUE #327: Registers are not decoded correctly in tooltip
Related: #17 
Recently merged: #322 

Seems that it's unfinished - the registers are not decoded, there are always zeros afaict.
Also they are too long - in that particular case it should be 4 bits each (since they are encoded on a single byte).

Image

### PR DESCRIPTION
**Pull request by wkwiatek**
Closes #327

### CODE REVIEW

File: src/packages/pvm/pvm/args-decoder.ts [hunk 1]
```diff
@@ -0,0 +1,499 @@
+import { ArgumentType, Mask } from "@typeberry/pvm-debugger-adapter";
+import { ExtendedWitdthImmediateDecoder } from "@/packages/pvm/decoders/extended-with-immediate-decoder.ts";
+import { ImmediateDecoder } from "../decoders/immediate-decoder";
+import { NibblesDecoder } from "../decoders/nibbles-decoder";
```
Comment (mateuszsikora) [inline src/packages/pvm/pvm/args-decoder.ts:4]: if you don't change anything in the decoders logic, you can use them from pvm-debugger-adapter package (I can export them if they aren't exported)
